/// GENERATED by app/tools/gen_state_cue.py - do not edit by hand.
library;

const String kStateCueCode = r'''
import 'dart:convert';
import 'package:archive/archive.dart' show GZipDecoder; // not dart:io - dart2js (FlutterFlow Web Publishing) cannot compile it
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:lottie/lottie.dart';
import '/app_state.dart';

/// One Lottie state cue (Add-on A). `cue` is either a file name from docs/ASSETS.md
/// (mic_idle, listening_wave, thinking_dots, speaking, countdown_warning, qr_scan, connected_check,
/// offline, empty_history, report_success) or a page rule that picks ONE cue from App State:
///   'room'  -> speaking | listening_wave | thinking_dots | countdown_warning | mic_idle
///   'pair'  -> connected_check | offline | qr_scan
/// Honors the OS reduced-motion setting (static first frame). Pure UI: never touches VoiceLink.
class StateCue extends StatefulWidget {
  const StateCue({super.key, this.width, this.height, required this.cue, this.loop = true});
  final double? width;
  final double? height;
  final String cue;
  final bool loop;
  @override
  State<StateCue> createState() => _StateCueState();
}

class _StateCueState extends State<StateCue> {
  static final Map<String, Uint8List> _cache = <String, Uint8List>{};

  static Uint8List? _bytes(String cue) {
    final b64 = _kCues[cue];
    if (b64 == null) return null;
    return _cache[cue] ??= Uint8List.fromList(GZipDecoder().decodeBytes(base64Decode(b64)));
  }

  String _resolve(FFAppState s) {
    switch (widget.cue) {
      case 'room':
        if (s.isSpeaking) return 'speaking';
        if (s.isListening) return 'listening_wave';
        if (s.countdownSeconds > 0 && s.countdownSeconds <= 10) return 'countdown_warning';
        if (s.lastReaction == 'thinking') return 'thinking_dots';
        return 'mic_idle';
      case 'pair':
        if (s.connectionState == 'connected') return 'connected_check';
        if (s.connectionState == 'error') return 'offline';
        return 'qr_scan';
      default:
        return widget.cue;
    }
  }

  @override
  Widget build(BuildContext context) {
    final reduceMotion = MediaQuery.maybeOf(context)?.disableAnimations ?? false;
    return SizedBox(
      width: widget.width,
      height: widget.height,
      child: ListenableBuilder(
        listenable: FFAppState(),
        builder: (context, _) {
          final name = _resolve(FFAppState());
          final bytes = _bytes(name);
          if (bytes == null) return const SizedBox.shrink();
          final oneShot = name == 'connected_check' || name == 'report_success';
          return Lottie.memory(
            bytes,
            key: ValueKey<String>(name),
            fit: BoxFit.contain,
            animate: !reduceMotion,
            repeat: widget.loop && !oneShot,
          );
        },
      ),
    );
  }
}

// gzip+base64 of the recoloured JSON files in app/assets/lottie/ (see docs/ASSETS.md for sources + licence)
const Map<String, String> _kCues = <String, String>{
  'connected_check':
      'H4sIABLmm2oC/+1YS2+bQBD+K2jPa7Szb3zrI82lh0qteol8oAmpXYOxgKaJIv/3zj6wTQxJKzU9RLFl1mY+Zndmvvm8cE9uyJyo'
      'VKXACCXXDZnzLM0MYww4Z4YJoGS1JXNGSY0DCJMy91LKIkJS8ovMBUPrEkehKNlU6PBdXW0TQIdXV1f+2rxti64l84sFJWV+VzTu'
      '+/3evNrgiDN1d2Quo4/Py3xbJB8dOJHoqm08ZI1X3pPaHXJ/7RpPuwWsbvEL7ChpBrbewtCyHVguQFoKFoOnbBFQHEH5EMQo25ud'
      '93ZoznQqeUbjgAuJUL1zrmqPa10kIWAXIPneYDirzp/wkbMQOQJJnKiPcz8RIhF/4dcSjzMwKQhNOQ5WLXDi2kFApMxqalJu+B7r'
      'jgi4cYCZ1Ckzks50KkA5Rzq1oChgJvCXlKnKBFoRpbS76pLMr/OyLXaHJPkKfcq7pa9ytcFfb96/PUu+Fpdd3SShdrPkvKl/bhGw'
      'vNq7iDloO+IdD1KdgpaGKWu5UDyTAIayVIPSVnMjFcssk3gmmA5QSSFmXezoFDXkznP1yMRVsCi0lLgUjsMPP3yrPCbQsGvqdTEe'
      '5nmTb5erSww0oEYj7Vy1HzBvJql5lHLThHMBHWgmTviepdrwnoOT2TDO8XqsUVye2nzMovq6f2nyTXtdNxXZLQbN6pK0wVAFltbH'
      'tk9lJPVIBqcI0lXkEDuE2H0T3JPbwBVpcfY7l5JFH2iwSAPRwlCsuLNis4H1/i7Yws+Bq7RBykBJYwxyzZtdbndH6S/GUsFPMssO'
      '9aj8emP8MWGrKnHd0o7z6MOq7FDlZokDDrKxCOoLcanMCGxZFbRYoOj49WvwHUFdU51CfQVcyAOx5dNiK55HbBXyVpvHpBa7YmaP'
      '1PiY/WMMwDrT/qi16dlA8f2QEZbGgxCi54YX9sCNWHt3ytc/EISrSBAGlhuWBZCxKSigcTimy59q/uG/jhQlOelwLizFz1GetlP6'
      'IPqWPCvL1bYtkqclOSJHe+66fA5RltMypAKDYCi52A7lU4LrMH8jt45Yz6S47L+rbV/tf6G3UWHito5xqwCU7SXGhhZw1catHw8S'
      'c4od1xgxrTH8cY3hL09ixLjEQMylVUpIowIIhV0Lv6l0w6vEvErMS5AYEamON5aQcfzvjBIDUWIUWCltkJhT7LjEyGmJgae2MS9O'
      'YtioxJxsCP0uF3BrbLGB+vFVY1415gVoTHxMJYyNooI3SVzpICqsVxEEV3mz7p9C4a3mXLK419c840KgoFy6JbpHWI2/ZPcbXTw+'
      'disTAAA=',
  'countdown_warning':
      'H4sIABLmm2oC/+2Y3Y/iNhDA/xXkZ8f1tx2e2muvfWmlUyv1BfGQQtjlCCRKcts7rfK/dyZxCIFlD1Z7Pa3EIgFrO/Nhz/xmzCPZ'
      'bcmU/Jxvi4kglCyXSzLllNyTqTTw+S98Sk3JNq0TMn0kd7D4xyyv63W6Wmdp9UOd59lmXUcfqwlnSjFJGkqy5EtaVmQ6eyT1FzKF'
      '51stf90nRTr5HScnFpRVJZkK+KjJNLKMt39Sa+UNh+G8IFPlZDsuDLy8g9F1gZZ1iwUXXjoeg7lg9SrJqnTw4J9t50hS/ZFUm/10'
      'krfDmwq9ScIbDoC1nCrBnKF8Dno+g23gSr9OdEseSY4DMIneKkrAPQ7L1vtRH0bDwyCUU8FRZI2WN/RQhLDuAhHeszgGIWCcGGQp'
      '+RJZVjPhqVNMmQNRGkXhtNPMKuoNk/HBdDgcoa1VYEYT9seizM1oD1F5ce2W2WB5b6MQnBnwVEsmJR1t3Wg6ZtbT/W4EGxVXylvX'
      '2wibRMqxieFw0YYqObE+H43AHoTlooHJdAX6QXKFkTwEOLkryRBxQyxudzD30y/v3k/+Thd1Xk5+K/NPBQnp8D7L1kWVtnnXqqBk'
      '0ZoM8xj7MFoPKtLsMhVdkkWTIP1Y2Yekvu8yvVVYHGdAH/vqIPbDpORU8v224mm0hq2yS31Pivv1Akz7dZ1lvV34vbVncWQJ885r'
      'JYAARsdcxJZCoBz+zx0cPoPkCibp7qTF2SM0g801nldyzndx6jsK6fJhvzmbp6JKN0/sqYZ4/Vo42ieisTf7rEeuaeZtoO+WrdXn'
      'cWuOcKsDboWVsVRK97jVAbcwppTscCvisNg55b25DLd1+emrtHWeCWNfF7cqBplUMK8Hfon4JaTsJGnDvD0AuHu5KKiOsTygKkRF'
      'j7SwoLN9oHKPNK/xdSF2+4gVgkmQBkJjRfk3xeEWjrz6UOZFWkJj0HGxDUGMhY5vu4eBDPkyRW7A8OdzOXRGLSZeUY/mHpEcXbTB'
      'AcxmkWKeo9+MSzmnswgYAduuHGy+g/85jbBwxALnNDPe0UhgvfPzeat3NoNzAtxEIMJ4uX8kVt13kGR9DF/heCzqkRaffMAnoTJJ'
      '5yikkUL50E608qGAWuVRIR76eARsgQare2Le9JnQvFaR+RPGkt1ddmmZKRfXlRmUf6rrmipTnouB4/IDlJL2VoCuLkCIw/+h/sjn'
      '6o8a1x/Xd/veCGG8CeXHm1B+rMd97srP6drX6fYjTSPPLu72tX8C9BqvJOeafdfT3XgGtbR7P7gKjC8x19IdRMm2Wee3TvfVO13l'
      'qUQ831BzHWpCTn172KjnYCPHsFF9ryuliKXpf1rwIsDGCK8xuxE2p2vfCGzU/gYvGbChex9gI4Jf3hilnfnesJE31txY81ZYo59j'
      'jRizhvcXaR/gomIr4Y7bwoW/GZrwniZe4pW0ex/u077/QUApwOf371xuMLnB5I3ApM2WB/DOMMMEBw9XoEnGLHZd28EdV6FFceGK'
      'oLjRXsiBIklVpTXG9rz5D2j2vN/BGQAA',
  'empty_history':
      'H4sIABLmm2oC/+1dWW8cOZL+K0Y9Z3EZZPDy28zszLw0MAvsYrFAww+atnysZcuQ1L1jNPzfN74IZt1VkmyVJFfnoMeqzGSSTJJx'
      'X7/Pfpu9nLGrzs+G2cfzm7PZy99nb+XeT5c3N+/P//b+4vz6xZ/++oIcaRN5PpM/H+zPa/tz8wv+fh1mb65mL0NzrXjvKQRffKRh'
      '9v7z7KUfZpfypxTn8b9IMYfCcZj93+wlyY1h9m788emj9PaXy4+fXxCGeP1a3z67vj6/uZ69/PnVMLs4+3J+hd+/Lx6//yR/Zayb'
      'L7OX3Pv4z3dnn89f/ITGL4J0dX2lTT5c4xsv8c+ZvvtBR5Y+/iU/SD7jau3Z+MTLk89rT37m6ofk8+BfWZvwVVdotYkf/OIx+r5e'
      'f4yB+/97o/wVnVxqi2t8gX0oPmz29ko+4/2N3tAv9vbF0nDWhxi/bzGEtJT2P+ssfmYa5hE/Ig/zUuXHPGaXfRmCd77hBvthzhFP'
      'Cg1Uk/wKeZiH+komeLnsSvpxnHgIwYWq7aVP7TKRNpc7mVxracgyBKOj4l0qw5xqdFUbSM/W8W/oeE4cBmY8oNgGYhsnBVmerHdl'
      'StHbmx5DF21AcaCsd1l+5oIO5Ui+Obu4Pv+63Bk9FP9xdvNOD9bHT3L1p3//819f/Pf5LzeXVy/suMxf/P3q8tfP0uDd60UXffmv'
      'b2ba8dr+OgqUcsVxTrKCXibuXVhe2VO5F0tI3Dw1We7KkdJAfcvj12HfeeSvCiIrj4I9SPLg4hfd8Iv/1T8fL/To//OjtnythwTf'
      '+HrWP/31mR6T39a6i+Px/orPRPu3Y/u3Z5+3mgvctnFFxxcuxxcu37wRIF15h2yN9Aj+PvuXLleNclhmXxa/x2+3pyS7Nz7Fb3kq'
      'xz0GBRyBFrT/HbfkKCkmCTURpZqsgZwbNOnrWr7il+GCm6vLD+e7N/7vV2ef373/RbbeWu3c+xuA3uct2D4I+LeC/cr+78Q5ef/B'
      'KOj0w66XcGSuz3Y9SSMQ/NfV2afrN5dXH2fLBdLTj/X5JF8piPkX/a7FeerIZcfibULLK8P4ghd0g3y1A28EgCrZxhUBh1ClRwGq'
      'lzS25VpL6WNi6dfQe9iP3uko6D15oHc/ofcJvf+o6J3CD4Deg99C76l29C58YqzAHhN6/xHQe2m1o/cQ2bOhd78Po8d1jP7u/Oz1'
      'v/3z8l9v319dhBf/+PXm4v0nwY/fgNp3ncy8OHu0cSrj8sz2E9nsvHk9jt95unnkTdJmb/eZUfJrvYADSl2W8okrCaodp/zqEEVj'
      'RyUOoTTHh453puRqYUHHQT4lHjrsNQ7y3/EpnAte59EJlCxxrcNc/lDQy5AzLkNO9pT0quBqvvny3N5Gq9ifZyBx+bc/JVwV3qSK'
      'clNE2v4zhoAuGo9DaBe+d+EZfQCnLacchJO1X3h3Pr5s72oXNnm8i6eeF9QzypySEFfnSWml8zGuXhb74KKUeB5cDnrtY1AiKiPJ'
      'Arhcx0sQKHsZXYXlRdFvt36sG/SCZ9bJ3HoxInxz9euD0uA3F8ehwbwf1SbDG7TAhfoRf3t/cXEbPUGbO1OT1ARjBgbboyt9IoRF'
      't3JBWMJ3EJbhIXAEM63hiCjiBCC1dKBcfz63BvZ8C9JTWUC61+PllV0eu05lhGW5r6Amj0doZWGJV8AzuJRpeSlImNsKdFrr/hRt'
      'x9/W0NpNAHdPgKvNNSC2yE4+5cQgLhyEuPB4ELdNlcshquzbN5HldDtZDkuyHA+S5XAXshzXyXLeR5YBrW0J2YJh8P1Lskw5rZFl'
      'X/IK4At95bIkywHyc38XPeUlVUY/S6rsSxrGTqyPiSp/I1UWFFubIAlZbzBfJ4Uk4kEkER8PSeSGU65ATS5WJYXsg4FIKAoxlEOn'
      'u3KSBBRatOahkR4iA4rUZLPkXgfu2PTo11QMfqKAQnTZs76aMiAoxmRcLonI49jwkkFQStX6KUnBkpgWqEWmVItig8htZLmVT+Zi'
      'jHLGVfbWYYxVrmrsTdnYb/atYyHSrlgHJNdqGNiF2oFb+EKw8Kbwks9hlWxK6FgwVmW7aZwtkT6vxZBqVYyWwgpSEhQ1zIs07Osi'
      'uGGYi0jXRvYfslMAd6EYpIUh6Mf3uUZZxKo8P9oWFRWyTibJ2ucBHSTlT4D9IBdUlQ9KUqZH5m8T81BIyt5x32lZMWF2OLdOGwiX'
      'NdcJb90Tb8mpk82UGcUsMFBPDG/xQbzFj4a3jKNIDvotwS1xU0jAvwvtdhbJWZGInf5+CbxWT1pjndY11mFNY01+HRC+W1F7yiCd'
      'nBeqEbwgSpCNkwLpdFD1nJ41SEPVvQLSkBImkJ5A+i4qiOACy0HzMs98aiCdD4J0flyQ9k7OAI6IMrFV+PsK3jKkZkwslAIC9s0U'
      'CwLJxmLnUuxaeXnWq44CTAiQfrMy38GY8SDIOaGn3LRn5YWVNcYYPGCIYLiCocnIajPfxi2wnzH0FCWgOTWZOdr7oIoCYldgxCeY'
      '2HWKVKVn9F9y56abyFGUXNIRYKePZaDgikoFax1OuGrCVbfiKo4uYUZFBDTIzyeFq8pBXFUeGVcZExIKgB8CcmDT44HXkJvqbyMA'
      'nLgIvAfVWKxgtDpiNDaMFg5itLyB0WxwEe+hQ5DRskorfS59KvMsPwTZCM4xvcstaC/eGe3NS4ASc6AM8VV7bq74PLCLiqoj7ChQ'
      'Cwh+U6arFJdqtRcMl1dBgXEIwIf6qVtdluyaLE5kl5NqfVMTLArfI8fmUiRYtPAgY2RzLFrvc0KXE7q8XVojl0IeiIUC06lZl+pB'
      'dFkfWVoLnRcKrpmKUrieDOwHp8Zs2JCpgBkKXBaYzl5bvCUoLWoT9U3ULtSI0tImjoJOTXi+AH2puT5CIleldSYzwEDvLM+LoqTe'
      'XhtNyMMf0ycPek9ZayFOQo9ODeraQbVne1yoywIZBBtCaGVNHAoGU2pJWAWb5BiuwcK3cC2mZMGNfj2BxTHBAmZMJhKU1IxtOi3v'
      'In/YvcgfETK2PEnV8VN9M/XXit+mOn32J/Kre3+aW+YaaMH2CXoW4T6vDKuLBJsnSJUxxYLlkvDnwo+maA7zLuUEYGrmJBTAYg/V'
      'UbfZ5dqUIKn6QGib+g6QTwvQlTGEhBWZMxtNZZ+GIFNQdYI8DYOOz9Y7hh9H74MDtJUDD6xekDK7PLp1JBUOSjO4x+iwfPi8okst'
      'RrMhXirNzlg/aZc8jq6+CIwhNBqGW8UgDTz/kIWPB7JJLKJRG1hEFZ1lLMKtV+ULlM0P5r2Rm1BpsmXNMC1X+EuUVRPjmiPuPTc0'
      'Tjt6jx3NjqpMQ960cBSS7wp1KBjPtlRkvyRzTcl2FM4YMP53w/S9dhRO0Tw6RRN7iLjTXj1D6Hs1cQCTVL2TvW9yjLzAAgsc06kZ'
      'TOiW+Jt7BeD4b4q44fWIm7Orj9c7I24+n12df7rRg/3owTdlDPaq3xMwI2izBt4Tx3OfjgI9yHxCeYC5xI21wQ51iheoNc5pdbIH'
      'A4GyY0ERLIAWOBwKBUqRtWmUgxZCeCbhrlD5+KJqHfnb9czjvfl4c6n03no07OpkpJfCtuTWG+lvU6lTruObdvc4bmuTUGvEIAa1'
      'BXAmOaN5Cpk5vkhLu6WfNby8oZsV9o+Keaty5/BLrYOwh3XpWxNU7QptUjRPUWiXKsxNVLe0r4JmELGehaFVva2ZviL8XMEP1yIj'
      'RkBg9et6pT1i3cGPIt7zVRXzFSLiTQSAjanBIAZXoH2fNSfw+VAdV8d8ly/DNaxRWcUK0kAj9NLid3/ZSLdOa7+CiIgln+qexR8D'
      'xvayHc953pPQeQQKnVVnEJGuoaQpxO6oRtDW1ATZejhLRCx2gyXSjJuJVWPV/cecR4SpJtsJS5cTIo1/w/2kwIa8ML4CncGIPYJk'
      'dInV6S3FrOqpJig3CbKyruUoD+PA8F6REzAOPDrjMdWBxviaAlAe1OsibkE024ySdG/9h6i+GPMUHXHoznAZoSJwUiljk2au9rF7'
      '0jQYZKsj8/fDLyjYssw8mVtKCoOMkZN628mgETozkWxam2xTk2bqDqhOTq/IIlEO/skZnuNBvVR8Cu+4Ndexy4NPe3KpJogISEJ4'
      'DBo9YFNQF9qi1gRoqkMaFg0EeZaC0E9FEn8gJBAnJPCNSEC4fBZCw5RcjHSiUXfxOUTdrf0r1LqAqVdXeRZaD3EtutwsQpU1F05o'
      'jjT6dh/SmOPNBqVfsQj7nuhOg3FFSqwt7EQtwjZUYSZEQGHlX2AhS01FvmL8CLuovrsN4bDKsQhfrBG2wkmZ2jEJ/6ZmR5mshQD7'
      'kIVtyhrDn0RgkdMfFmzYxI9MqOiwxw94V+KBPbuKUzhFCx5N9DL5Z94FoHtIXpbOR9EL4L0t0ZImF5rDNS50ASupgEWjhBVVwsqj'
      'hMULCWtuHc57j5tcUHbqy9B62AAc9gV1qZ7EBJ+CjAnCCmWV/xI84Ad4U2pf5DiDyTXvDPkornLERA6LE1KakNIdvHOz8twMH5U6'
      'hTs+tsEmjo5s+w02RXaoFsEm1TQhRcMEEWUYl85KwumkIcOfadSQB6QYCh2lrWIcRApBF9Oa8DWWV1gdh9XtR7GZ9JNSGQqSs8Tj'
      '2GsqK3PFlnZ45zfV6ABTIY+JTKD2jxpDYAGWa2gUiqOW9auoZ3RpmlumIk4qP8BnbWzVTmPNj75XoXzjXlX1cBOemNqtW8WySAXR'
      'F74IUeVH2Kv4Q8DV3Ww0z2vak4lmYix2MhYFKABZqaog5pPLjfIQwcnf5RWY1r0C//yP/3mKNNwr6bM3PQHpuzwBheJkehBPQBco'
      'P8icwGD4+BAegVlTsK3NCSuXRz/4lhLHtNJgyyvw2jzYBoyxsqXciibGXADLlwO7miCb9tTnrbUDidE9hfXdhX9hqeHui1CI+5O5'
      'Cdnb28wlQobe7NPXPPY5vnh4lzzC4/s04QDftjY9clp0GVLZ6JLLclmWM13dfBGwZVpbnqUehlN9sYJv3eg2+HFtNBSWaeEeKuxq'
      '3V7WvQdi0WiB6Xf4fwqpTkMSzJueQRp4xooPc/aIPrjVWoSgCNbW7NPuPCwuZIbGI3eNR6hJ5FdXTfcSes7C/hyPRSzozyfvz4lx'
      'uYVxiSKVVJS9EZhHIO1p+rDGJ0773mE9iBSNzKv1QE43+IwgeCo67pFYmUw8oUnHeVxvseiz0xJQoXT6NnmLHctkkS3jjSY9XkCD'
      '3uxVCXjLcoAibEHz+gSzctr13G5MoHFM0OBSYLeJCVmPwpSF/IiQEauICU0zZ5nFC8a0LAxdXqa50MRQQ+sFP5DQWiiLttnySE7C'
      'FiNfVUvdyXm8IVyzcv8/p6Cqi95ggqOJabydUFY1+RqhnNyMjoIOINOVhuT16mNcovkYw3DO5hyoRn+5bwk2c4XL9CBIQIuBMMzw'
      'FXZ9y8cp7L0gcEZWz6WZP4t07VG9snsxo+hAij1yRGPyvXbRzMbU+5wvOlWLxoBsfE2D+/uU4RGwQriTjMlmq1JfbwKdBwqqgsbU'
      'EzITGK6hIQst94R4iKNA8YteqKS/k6Uzq8NAMr0E2bf3Owm7E966jYuBy23MA6OYSpxckp5JCiK/w+7HLsBNCO4altsjNfWMtnyh'
      'whxFrjCWp7QM1EL9EEERofYkoQzvRXWDpGBhIh5ukvI8buYGE0zEWg8NSROBcJQ7ykOCT6eVJGlwYxOeiy2sJDR42KrqLuW7mGzv'
      'tBQwXY66zzuuRzrl9Qi7zgayvkYN22NzTkWK16IubJV7+A1oBaJylrQO6RKRVHUuZM4StW6uRzDLP6hXu209IqkyH45qbLV9SgZR'
      'NM1vrxF9nCVBNRyaQGaxHlW5lGk9xvxf9GOCTLvXkuT+4XRrfrs8HY1xLYRb3l4LFMxKmkw2xfokqyGSS2yM6Ef6ptWA9bB06yFF'
      'sKjx1PZ8cjyaRJqdIk0oIvbLLBOyEpycKuZZujR/s0wzRwELBF2xK0oAa7LSqAmqHEVRsUQEWeW4NIpA+1I1Q6WhiYoMlYjM6jWj'
      'kZAuaex5iHkDCbWMYOABEWhRc4yTz6g5MMgUqlFcgnpGBgANtloDJMxCAVEPULCkB6M+u3g0xKz5qrktrS7E6pKkoy1JXF0S8uo1'
      'JWNwNEUY7qAcA8kixWMuCclu5Hzfo/JI6/KER2Wn2KcEEmVQERBtVZRYaKzWDS0WHSQNakG0UGxLLhb5SZOGURcrrlThLIP8pd7c'
      't5HGC9kWCHVC6dZ1QTb9YBFUlkdc+BfWhDBc6airsk/y+4Mjlr0S4B98XSL9QaDo+4TBP/gpSWGnsBThhRRQXDnsWBKIS8hfI/JR'
      'XhGXEGeOaoKOTAO2sShRE1RCBqOt6gxbawIPqJY1B3W1JUHSHBG/RG66I1W+m2B4Evs/CYiTgLjb5lWRLGtIKVj+qikw5SEDU/J6'
      'YMpP52+vHyYyZW0hdiVIhkcWoh8SKHI9nCD5WTnId6TrXQHTIfIfdecDhuufHNaukEa2/zCEEdeN+jgo1VBTVDMXeOEghNqEbCyF'
      'vJEG1WxvBWEKcwFFdvSdOZmnosmVwH8I8PYqCUFrHmT1dkgVirsBFQhDntyiJlR7e3YBLkLPwyD8itXhmHzpj+YlKUg6o9gwdOkH'
      'CqQTWVmRPNYqsWtyJU6V8CaYvktGNeO6ySPJZ8wnGhQQn0NQgBZBSDti5oZFUWBOq7XP+/X+F9Z6XNYaypqNVSi/uTUWVBUe0wgt'
      'r+fLBsgXm5c3NhtsdLDW/+SWOOGYW1O3yvwC8hELU9pqnZK3PlbaRpTlDsgl3U1RZALHreld52gF/ZjAfc95FjycsS3OfG8SWFQ3'
      'Q/oz6plgSnI4isjCaJmk4QrBeeWGoBbyDbXDgxUTz4LRtNqaK+YHrbXrkDIt45D3JNoRESS9l4nNmVDQrSgILi4JKCiw8ylNIR1H'
      'lF1Q4FGRRaQxfXyBRQax/KnrPogKUlBxXsE/SAzd9eiVrdqjJgEgTRgrmIt82EpfL+fOIyJDOrf8Rqm6RigsTrnneYXiuUIbAt4F'
      'pEi1HhzShDqOWxQ5E0pPD03IQPDpROMRwjNJkQqCnVwL5RZ9QcuWylnpr15XHDqaoOHI0IDgHMJRTqbBPUlPtvDonmx3qGBgVQdj'
      '0XN+qJ6BPCaI1FsWTZQ1TgJf4GkJVU+UH21mp+0Pkdfc6hrAFZa1/kqLsefcyxlxiC4tilRNIvNxwCwm5xsUWlxOkNMrB+GsPD6c'
      '7Sc2EALLgGiIbuCX62zhEblOxOa4hcFAZDK0usXlempAUA8CQX06YiMiToUZtrgwpi8rcAtDpta0W9NSHCVaFttzrUDS4bxp4oWg'
      'o2U3smbw08KHIVsVjGYeZsJgpBj0GPeiXMJzQIzqet8AFwkeeg8TAB41oUyFdxUbBPpyasHY7SAEtmccuACmbI8vLVtlPnhfLLnE'
      '+WggE7plKso1gaqZWwel6qI6beCGtO7XD+ZIzwr9d5+23R7vPs2kV7N3/kBrjaDQnJ5qreHXHFyqtSQSMTHm8kQLOHlcHkUFgHIw'
      'BeHJcAM7LQcaf7iiuv8BqUJ0Hol8RJjUyqVLOBPmy0OZg9CMtpXSFupvgqpZ3cRR8mKwy3Z8irBnygkavwGO2JTKU0x4LzV4vmu8'
      'lxLcYY3zd034TlTg2As3UYCHpwAN+XF5qKjE3k6OAtBhCkA/olwgcnYLSAqH2lqlrnhnRZSfHLCjdRPaUd+NAWcVXuzVxHWKApT9'
      'xvEFA0LcGKZdtcjdSgxTqmlogl2eas775YLnvdb7BYNHWOu7yQWPsYATWXh4dW1N8IUQwQChg6dWXocOp+amcPw4prJRYOfy9Zdj'
      'xzE9IEHaFQt1c6nHYU76rt55bwdk8A9FUBbjCjbZGNc/4JCr9ODApz7okCuo/K5fuVjqQ+h4e/5fn3Hg2nef0Z0R+KQVN6CLgrVb'
      'qAneCAOqf0M9ljSB4OB7NW+lmhqAjHreaSzfHdO267uW9ZbFnYtgs5pWX6t/y3CsmYE1BTCcydSGMo9CCZEaTtOOL7qC83qET5rw'
      '4Xmzjg1mHoKaKgtvZhwn7LslvqqaJAvZfYmLyn2sSjf8SqENpIWGggXfedhitO6vlSwvDh62pbm4qFusrrMMH1rc0QLrylWEHoRd'
      'yAqoU5RZWz1hOchB3WWjvBbo4fjK9CA7yw4x6QGZZrov4NF3tmkZEnBCoeYn2Fj4PGt56CzTfIY7uzv3zASzd4fZimnxM9zZPO3s'
      'N+6slk3tBpUa6Yh7C8YhWs4OacNEZdq1Z01DJ3F3iinZrctNTU8oI7ggpCkc/mFF9rqReuTsy/nVizplH7mlPGdxtUABiJiboEai'
      'gNLtgvaCEhKk/EU+5AI3WdwANYpVi5VYg6qFxq2gexij9hIBOcOZkHp5s4qIzoiqJbGXdUK2EuR1IkXgnF31ZUhFy7ICxQNvt6Gi'
      'OPyKjjQhMbO8WOQ9yxssmLoOBTVtra6L8EBA8U29SLmZtwUyaqoBqwkUCoqnwJpKRd5AsKJ8YSu90AuiTpUIIMpQy4gi+QoJ/SlC'
      'W6xCPby6ocKt0pa6D3dGujdkMa55JYIis3rRzZGRliy5S9AoRniAy7qQ5cbHEJr504tA0tPlgzYXTSZe7E4VDIes5AHJ4jRaCVnr'
      'ZP9YviYrBSMW3k+WA6m0QHoFcjpJQ62bhibRI6uM9Ct7mhN1V0BNVsfyXbnxkVzOTzheUE4lUl8LiwTO50Rxe3gs3C6NP55dfTi/'
      'ApJ79fX/AfMcy3L25AAA',
  'listening_wave':
      'H4sIABLmm2oC/+2aW2+bMBSA/wryM2W+csnTOu2iSes0rdJeqmpiCUloSEBA11VR/vsOxkBJmrYT0eSkrtRAbHNuxud8crxGqyUa'
      'oTwap/kkXs2sIovGZX67/Hlx/vkrstFkMkEjbKM5GnHft9Gdui6jMkSjNZrB02+TtCzjaBonUfGmTNNkEZdnN4WFHeo6BG1slIT3'
      'UV6g0dUalfcgwa7VXs7DLLK+VJ2WB8qKHI0IXEqpMs3QyMUOrv4o58wXGDrjrLYHzJqGSRF1Jv5a1j1hcREWi7Y7TGXzoqjMDdVH'
      '1QDmnHnM9h1h42sQ/AeUg61FfwjB2Fb/apBbDVr0RmFoyvrPMTBd2JQHrXAKg/L+Y0pr9XgR7khMey2VEfVwsoHOaApKQHJRxbAL'
      'LZrlqAtFF6TlCvrO37/7YP2ACU5z61Oe3mZITcR3aAtXsySyCFJKbDSWRsMI8IxBa9kpyccvU1JP8JlVyd/V9S0s51LhROrbCiBu'
      'A8d2AidUKPiD+SL1Y+s6bNCJHeJ6NrpXdzA0bnt8xlQP3NVCrlgzyaUM/zBBLqsFiaGCGovIUJO4UIIOZhIdHCXMlaSD2cQGh4kq'
      'QQcziQ81yVfvEj+YSWKoScxTgqRJ2+K3s/amzYDVaJlBivKlaSrM5vEYcshlmaeLqMki9TeZPZKxXPzJjbwsE1lf9uTOKmHcPZaD'
      'wQ803kpADha+T5mgASfEc7mHoVI4nBHmUcEDTAIXe74LbazXwhlvM1fr8DT5V4c/xknSuFvdS2cPbyOvsyvZGzPROVFWxSXcl6f3'
      'V88HiXy7cnZGZDu12eEehfoMn8+VUPeRCtpN7B7HvM3mWr6aq4k0fj+cuKcGJ9jAydHBSYMUQ3M3JUQ3NiHU1w9OXKwdnBDqakcn'
      'RHDt8KQhph6eNOvH0Imhk2OhE3tI4ZRf2qJJ+0WT6FU0H6mZLavUK3drif7PycbPY9JwAKVPAag4MQCl3ADoqwVQIoRuABoQ/fjT'
      'd7XjTyr040+KA+34k1BuANQAqAFQA6DHA6DsKQDlJwagxDcA+moB1Nfux9l2E00nAKX6AWi7KavTBmizea0RgHZ7/AZADYAaADUA'
      'egQAyp8CUHZqAEoNgL7e84Ht+SltCLRhYo0AtDmKpxN/NicWNeLP5mCnTvufLjPnAw1/ntL5QFHd/QYfhSMcCm5OQRENnMCDF5lQ'
      'ij3MyDNQEhZFVFaL4XrzF1/sao55MQAA',
  'mic_idle':
      'H4sIABLmm2oC/+1a33PiNhD+Vxg9C49+285bO71rHzu9Tl8yzI0vkMSNAY+hzWUy+d+7kg1IWIYEAhdRP1gOK9na1Wq//VbOM/oX'
      'XSERyShFGN1W6IpJjPISXRGM5nCjVGH0iK5EDIL75j4ej82AbLGYLBfo6nqEUZE9TSr99/O6O5/BnWK0fILnMJpNYaoyL4rBEt6M'
      '0QOMfkZz3WRm/AOMJuQFo8qRaUnpSK4ZjzFjJIolJiPoztxuHkk8ZOm6e+F2wyR4qBu4Ri/68bnpW9xn5aQ2QauM7irQMl9uBNUN'
      'CGqbtl7JVKRYjKWMZJKM2gqTWhHXMKYtM6vyx+Rmmc3uisng92x5P6AwzXQG8p9++fnT4C/onFeDL1q7wXCgx6IX3Ki0nKJtZbTH'
      '8u9wh7dPnB5F6x4GPe66k7qDQ8fU2GeGNdr9WeVTo9jCr9nnvFhOKlBND9yotljC4JutdYgILBDjkqWC0ljBdgIfRYJTHjMpUkJT'
      'ReJEgYw7EsFFvYS+/fLoyARIihtjRfG3uU2LzQb8sqzmDxO/Ib9WWXmf34Al9ShrmfVWKLd3mXb5kJMooXK0Wdms7fqNQzxbUe/C'
      'zfJXPr8on+F1V6xf+uB7SK/DIvP1yJe1Z7PZ4nZegddGra2ol2hWmpXzrNT8n9I8pLEClFnBhfkLPK+n+jatw6oyTrjPx+PJzITz'
      'FkQwD0SM54+zH40RlwsRpAshZNIjRI8QHw4huIsQ37LF5FhwUFFCGGax6EAH4EFMY8R5wIFHaYppEvGUnhMabotzBWDtYaPuZ43v'
      'e6JLj9kXWzI2LkpkcmhowdNxKj98ePFTh5dww+u3rLgdVPnd7PgYk5yDj4SOJm+YAQ9X687jo2xTb6BJ0cp610JEgilc37rjzCzC'
      'p6LIy8VrQqoZuTPhmqrKm3Fj+X/IuLzJuOzkGVemAjaVjFTKDoUFHkciobi5fyBoWO3JN+RdXQyu6/g3woJ0YYHQY/FA47UfCMAh'
      'LgbQWv6Mci34brapUjG2WjDxSbsL0+b3yhH1aA7QY7XNaDOR+a3XGQSIlPDsV/qVlCD9SsDGLsmqNVLdInhpvaSLLbwyUQ47CX7x'
      'BsFwELYwFknFGoMs9RuDbEgOwyBBI67kBXlIsYiI+II8lEB5dEkOStNISXpBDoLcAWRbXJCLKKeRMhnxVT7ST4gEyGxCEpnyWL68'
      'EyGlaRIpApVffT8dJX33Qo+erdCD3XIxRyfbBG5/ZUd207cWZ1NbnI11cDbZUzY/mAH5MVeglM1SvzYoTbE+WgqTsG2UD9Y7Dl1r'
      'eSfA3GnTtXbmfKuDSJRqQRq/g1WkTGOPGV7hK6hb21mnpW5DSMiE4ea2y21DUhKD7DvFO+hcN5Xj2FzHWkjNuHXrOI7Wo7fsolpX'
      'xyRXsmrpqvWSU0v/YBHDJad7AL2npj01DYSaxlvUlHdQU95TUz84p/ArDfc00VK/MQhSrbkCPU201F95SGLafFAMkZ5a6q+yJ/hL'
      'BUtPLe0PdBAwU2H4qXgngiq8DFUcSFHbDjs9RaU1RaX7KSr1U1R6HEWlYC+V4VJUS/9gUcOlqK1d2FPUnqIGSVGTLYoq+i/e/Rfv'
      '/ot3/8W7/+Ldf/Huv3j3nK3nbB+Os6UuZ1tqHcqsmsyW7f9X7OBYqyhtR+cqIjsj0cMhVjElPdhw9Ex2cpfNRIycYiY767KT2mSl'
      'w9OaZOeptUknmclJIMQ1aoPGjJIGW/tiwpNmGRNYX4EWE7b6TZZlMTZXoMWEpX6wHnJgre0hIbG5wiwmLO0PdJA+6hZ41b7Hgbfw'
      'HniLg4oLj8POcOCtcHPbe+Ct/Afeqj/wlmGjhlM+tXdhf+DdF09BFk+UdFZP7MjqyYKYTmjZJoCnpOQ2NbOyx6mLtFdZ1QFu615f'
      'Zt1Pb846sUVDzjqvTQ/OOrG3xOsrvLdVeJAa9BVqhWepf6GfiwL0kFPhXYKHdn4uCtBBTkV3Ogf9qHrnElzk1jstH/X1Tl/vBFHv'
      'jF7+A9g2pibiUgAA',
  'offline':
      'H4sIABLmm2oC/+1dSW8cSXb+K0KdMxOxL7rZY7vhgy+24YtADCiJkjgtkUSR6pl2Q//d3/de5FZkUVRRW9M16BGZkRGRsbx94x+b'
      '3zbPN3GIQ9l0mzfbzXPnhxpqramG4oJz3eb8avPcdJtL/LDODMYY56pPxvrUbf6+eV4M3r7DS8tfLj5gwr9cfrh6ZjHj69evZfDp'
      '9fXZzfXm+Ys/Nudo2bxCh78adHh/+vvZVl+Mfc8v8DN2m5vfN89Dm/A/z1593F5f9uHZq8uLm8vtxeU1Bl9jvbbb/Irxf2wu+c+p'
      'zPArmrmW839wVZ+6zXb1rs/tlcGrq9WrF96FodTUeVeHFFxnTrSvQ9fTddfqB1NLV9NQrZ868nPXt+bs+H+sqXVKnzjdpfS4fnd6'
      'daYnwB1v3m6xs/MbPasLPRJ5cf1u0z4xbvlUf9eubPiH9P5dV3E5tgwuSyO3e6PfHIe8eNG7PAQbut5icS/6ggeLBzu4ENgQhmQS'
      'Gjx+sgEAUL08Z+vwnAdTONoNzmQ84xcTStfnoXi+t2GI0mEIXl/n4rqIw018NIOvsatD5cs0lOg7dCmWjxgTU+wwQw6Rzy4OPtfO'
      'Al6zPTmRLb54gaXELgyVX9PlT6vHt33u0MEnywl08dPasUgfCz+YsnxP1z4uvceXvUH/IZjU3nPx/bh6nNmQTebZ4YMyRLfQT3vw'
      'g/UYQWgyXALBK/OA4+Bi4B5+4x6CwUrRXDGucFwGcGXMnHL7Ft64YmUmLz1qxZDCvSbdOl4k30U7GM/TihW7TF1xg82FR10H5wmt'
      'Qc/CYSDgFsOC4fs+piHW0CUccpS9lIA1xM4brL2yARBvebfYbilyYsEOXm67YJ+e23m1eX6z/Xj26eRT9yVASVqyhEqLg6xdj5sr'
      'ehU4DwFMA2wTwASdqgRMrNpxLQ7HEeXZFoUsY4IAahDowQtjKy8PEKfP3IwfimwO5+hN5XEWAR3ccXQEleqDwqIvmaAXBMx7HFuw'
      'fG+LwmocKm4ek7o4g2bCLCAmA8gJv8FNYFLuQWCjYAEcKCvusYOSOm4ojdDFFQG8c/sCbgPLHz8XIg8ox9aXqCFXoy0g6QA8grDj'
      'BoBLWU+HT1U+zcOp2bfDyWhIsp0RKgHFgchfeQpcYsQ1Yz89oFPXWBLAGKsA4ggxAMzJIRV+JFt8zHaJWMgluTRkgGDJQ9svEAuL'
      'qtiXolPChgPOEKcmV0QIDNV1gPncTt0DiIugj4nSJQOggXCAdgUUX3AQUTEp10dAJIjWGiJB6QKOcMIGbMPjxMfd4dmBXeIZXFNJ'
      'qQIgtidnDBQ3XHomBVBS6H2SBuM5I5gr7wg3JqQDCAv8JfFzjVJiOnROVWAJ27Qdhlg5a3wdh0jgKQo7OBZbujKkBTiCOmZwKswf'
      'hXJz/ePyeaLkZtiEF0JKeBAoc0o5Iyins40MelmJCQqLoDwA69AID58rwSaMgI21W91oKFWRyQkyl0EXkhVxS6xtJQTdLJg+wSJx'
      'oSezzVnpqCWhLdwhKX3kmvqMZoFEAFkmoITAW9AGwh7JLJ8UsDIuXTgPQRPcvrpxT16XWNEvKSh6IQgA5qzYiQYDiIncu4AmRiTu'
      'Gt+Ick5Yk0ncCPbt0i1QvKFwgqPC/0p0thrg85EzHznzt+fMC5lWpOv/3p7+7+nrS5HYP1yg4Z/+5Z//9dn/nL2CpP3svyifPuuf'
      '/bK9/HiFDu8gkr45fX99JjBMwfTN+43MfrdASrjErklZX9iTBcHFCzu+MCcr2RSXF10FwOQUsokFV4t7dAA20CgQSwcuBFZJslLS'
      'shkgdT9uPW7mdnBh3MVtdSOqtoFTePlBXjb15f37s4s9B/zL9vTq3fkrHPG/nb9/f+cJ31AnuLqlfgA98379xNynk3DBsz7ib+lI'
      'ZlRU9u40c9Jf7xrE47k+vetNXEDcxfWby+2H0+2GpyqNv2w/XukZXWCv0Dxfyc6mo2y6zx0HuAuZJyut1QcTCAoQWazLlZKmgprM'
      'q/iwTw+1az30L6dXp89enz2TpV8/c4croWa/DhowLEZzn+6Jlw+43c9pnCefUe5Xx9TtnIxbn8wVju/y4vRvZz/uUHa7HH4wB6ni'
      '+onGvO0AbgiBoAn2ZBCQZ0pR3lZNpCDpTVTeB80CrMuGLHwph0DhyQgzseSI7BxcmRir7PEFpxUxSabFeEfhzpImgM5VPEFbEemI'
      'k0Odok7TFhQ8CR+5x8joKFmkIDzcRd90rogG9KYQSSEAyoJIbUnFh0oOW2gvEpUCP6n/GGVieAseWCBgrUSfb8h6Rtx4DIn/iQh8'
      'xAlD3OlCwUXZJ0fn41eg893jEbUnphAaSiVUK2ZRvoWea6aGqdkXqiqDCtz6Cpck2FxEURhR00KWXIwEBELepVBaV5OuMRoKM00U'
      'mL/YnW+DDni3XNFQEwE7i7I5L5tIB+HcLz+dIQju7sXQkMFPQWmdaUAqUN2hcFP8blaEUEBkvB+UduEELJ8jFQBtEC1jaoCC5HJa'
      'NlTIqlWmqKmZBYCCYjTwovBl2gGCCtDZqS3GQhPGCCsaJxbRzV9Ed1pRFg1QDqCa+UAK2HqUWjk+JVWOSWId5eW4tgkcqdFDqVHI'
      'NB35LgBEXIlPjhyle8mR+17kaIXykbY7cG3jwp3kgizbgCAl9LC7ZOW3poHnVMUMmEozKmXIImTlZVSkLc0+KdZmu+F7GWDiEVUO'
      'QhVaI6Cdg2+XmJ4cpuR7McV/L0wJYDRV7PlBDHJWza+W9lerBh/vxV7rvL3FyAFEYquFntNsaSHTF6DmrYI5MbSCXcRRHPBqXRFv'
      'gNh0xWQZ4mxepcHOZU7jV6JAsmDJ6kaYWLKNQZ0ZVW1tYHQdVxPFNsbF9FxNEIWgJtBdMGLbiAKtxg6YLXJ2HqKl38GnPPNxvI20'
      'FgZPQUROg+YCnEkQWiL28hCFxaoSEqrYlyO36pr1MsUuuiFWoRSe2mHtHNSDql+mrYl2L5pSuWxL8y52H8VfEYzoB16MmGTikDh4'
      '5l74yJGyHEZZPCAOlwAmTH3wqZGWci9pCd+NCdMCLKTE5tEULo4eMV2DuoN5koUWtWQXGrbpOFE1nKQCQ5IiGn1oBHvglUu7MvjO'
      'vxMh0QWM3xfrtokkIur6JN1Jgap3Gp0/JlL3j0UdD4MTTxNWbOtnvqm2d2gdtErMFAR0oGYRsq1Y2IHsgZIGvhzKuC9jO9IRo+4I'
      'Q88p6YONQlNjpuAiNny16QdoFaRJkDCE5IA0xE4gWohugNJEa4NsVqmwrdglYN2LFSOBxNNkHwD84kCNdETRFA85qRwpykEUxViQ'
      'eboSmh/9iVGUei9Fid/NygCUTF1yjUisZRErvisQmflVogUAgE1//Ew1wlAFnxqHNuIE6j1QUByOmCHaTppFbmCYgUQbqJ8KIEuA'
      'rOKxI7BGPpnZqti8/fS77lIqWaPMrXEAajShcy0vZSvKBFWlLzqzIT9A7KiC/ZQeLDcZR2mCkQTA3Nr2QhQSm6hvRovER10t4xKA'
      'Ob0L9JwtxBwArRE5Lk8mSwaFhNH0Skop1tRRDvJ0FKZFQ+Tx0FEcIduJhgSMIN3BseqkOQ8JdGt+BkGrNOeKXzHS60dPZQJxChoj'
      'kUuQhqquOMegECctIYuW5YpcucV+arPIVroX0QIQqeFIyw6hZb4weCd1QQw/T086suZeYpa+GzGD6uEo6JucpkgUQnRRdceLuOM1'
      'DAvoT09IVTMlRKhCjUEDfhhFFERDEzWL/oc4vyXSJ45NLaRlyJ6xVCnNEQYMqIpCstTQB1D2Qqai+CSwUldkiia0yGr6cTm9rmf6'
      'oK6HywlNCwyeUpipTdBzcd4ZpRUvFCvNFAmILYpckCUDqY0cRh2EGlG0cUnjXkZljp4gtNtGwTMlnumZOiAVUQhOumDOUES8LMZN'
      'AxwjiVpMW+WR6esjETmEiICgJ+jbBaKv6LVPjYjc71/P39fQ6YHUDAEEisWHKkf0G0gskHH+s8rN0hjqx4AnB53D+6aSRAmigtqS'
      'bWpaiQMZUk48BhuF4JYto3jGELqisUPekXuPs7R5x4YjJh6kmriBKie4espPkJu7exGxfC9EXDPzfubmKruu2Xm/5uf9DkPvdzh6'
      'v8PSZ44em0tzl6H3Oxx9ZuhRBAY3c/MdZr7m5WtWXhSBR07eL1i5yuNqaVjz8n5m5rmJ6BM3V+eJ8PO84Of9kqE3eWRi6BrxnZKy'
      'c9vkgSU37xfsfIziPfLzR1KRCEXNV/DzopHOT42M+HvJSP0Rjst94Q37GDOoDYOH3RAFLcqQjJdA3KDRv/qeDUV5NEPrneQZ2HxE'
      'i4PE3BxFtSimgmI+vegiG+4PLzJ/BrzoNeKO8qeqg8wIEkwYXYwQQEPLMYm+ZT1J2gYfj4hxCL/wYPNJ8CI+Qee9/UzY3SHx1V8Y'
      'OOzXgcN/P39z/tfzV5cXvIvT7dnFjbz74gjiuxIP3L68g7In72CVI/YlEwSvM4R48BTQKGWK3q9yGHCytpocrS1xWuXJ/kBpWwvD'
      'FhghQLOTvS9iem/fHxk6zVhnUIXmmlz8Wjwl+iLZnobR1aGFX87NloZfCvYp6kurkdaaAcWfVR/VwSHzh3l2/liGWevX8a9GYrto'
      'p5DPqXObR7/f7yxAvlW6cQEM/DBh+Th+IKz3NH935AXM+/OMplCrB1OKnARXqOFPQ8wZW6HJrdB/oKt48AljF+9NS5hKohAtHg30'
      'IW/xI2nuK87J2+Y4ipjUznO1sfqpb8FjlokXM7y4/aH263sZ7ytLxmBg9Mx0e9O96D3xvCfGyt5MxZzByIETlKVXXqZvDvfF3OxY'
      '4nh7vX6qjW6ZyPPcc187g4AMnYzInl6hzjEjWaxLmicrLvgWW5+9XzwTiSUEoW0ui2JtqW0GTW5kWu3yuTC5U/t//gbdYTfodm/Q'
      '3y8jMVfAS9RCGUOLk8Quznc2XvTi1Ea1O7TcPjdGKdO7yUiw6fqYtxA1LMLYfBsI9HrXZEVt9IEmiHFyIInYMEyyu/bFllXtpggp'
      'p5mtLYCTUVkWMveUQoobKJ7BmEHNEJaGAaZpWHETAsUY1zw96vTE1YfEMPvDbs3v3lq4/9YAnFnSnMuUm7lDAnltbk3DFUF5PsVp'
      'iuoSzxhCIlNi6hqXF5VivIPkj1BBMUTMMYR/t+9ymCJqm6E3JxWejXqYfAFXZq4nLlAjVILEtFDf1HB4T2uTNBRBvXFWiQR8yK2E'
      'wyTuDx847oOQxbHCysvzi9Ptsxud+PpuOgvR9+Zsi6n/42z79uz/nTAPkQmkj7Q4gPhV+2STJdMPTqIhCvmVFqtNU8Oyw/LNWhG+'
      'Pc3Yd/8XJmVZI0z62son7D4DqY0IbdbU6ZFPZe48jd15uxp7VKsPwETH6D7G6uEgGbPz5DDR/Rz5Iz8TJjICavRrrBsaPk3FTPR5'
      'emz95/G779fjjwj5KISMWaP4nhhC+q+QpvIQOxeAkGUmas4mBQO9bI/ZK6zNXi8/bl9+/Nvp5k9r6eq/gqnrlqWLiBRKMe4hlq7o'
      'g+TbQMsbnK33GrqMla5Q/jSS9acwdEnNsDE1N7qm3vAXUyfSOjb3STKApRKaZMnSaR2lbkCcA4fpgZcU4LAIqCF9Jr1kIn+dCP2+'
      '76za6UoQ5dSx4heL+SxYCUsHMVKWuUYL/uJEBRZPHRbrJDuJZaTmUk4ZOlSlOYILZ00nSTkcgmb/ymuWemrZWKx04sPcQUovgT+E'
      '0cteHCtodVKdTFTOyrTlzAo6WdMaC+sYOZYaa3EMsUj1pGLHyEFMxuwlTFW/JUt5+2azlxIKjK+o/1t2vFLLyS2iLGFqhrEIkgZe'
      'mf/B3zx/y4kGxEKuyZ9WMtwj35cplqZ+ug38VIjT6PYgmT1bv+9pdSwnM1W/Ecr6bk2lhzzT9jUmOlykxrd82mFur8/w39vt6eu9'
      'pztzul/6L1MDAUvZSNJcoQn4yfG68NVr5nyhT2enXOtLIMnlV2Jte3iKcw9jbA8d7tr43toDZwjlcSuobr2C/TWs7uWKPrMQX+iC'
      'lQJl93FFdq0g9YGGyJp+Fu8PhGVJC5NyODQG5tRFPxbT8VJpjixhTNXNzIAPWat2eqe22tyS8xyTZX2rEdpLkbcilntJ1qACEcV4'
      'adQA34LQAllNx0psVgPZaLWvWtzRisLC0LM6JNu8KzEwtbWlIuOXBDEJrET8Q/TWGy/sKs+8Uz89f3lfRoth7Z4k/DC16onGtzAA'
      'U8d0m5y1uJ9l7oOmlFCu50DLCoEykKU4khTFI4jY3YSZKrE3Tu2bIRwDzo5ZKF+ehWJ/SKWMoJU2BdKDBmRnxpAxKyss6vpI2VCp'
      '8qs5631DLlZczHfX2AiK27hUzUxjNhc0ibTK53VJSnXQoxHKUhbm7DuTa36tFOqSIjhq4wiQm+mr9qz1mFo9yqpFB8yIzxxCVNWU'
      'fu9E/A7jCDxbS3HcCWn0TEnOpEIissfU9H3IQtYecfsg3A5GyrG5IhWGnh5uf40qOI8SJMtakHx9vj179er88uLs+ptUFXR03IGx'
      'JzrTk79PWJq6Sva9/ymEpYfkyzwkM4YltFjdODDrXxVmVgHM4oMtWoMr0y0vkoJ2mXpQ686aF1uhYaKfOQblHmaTdSDZ4GOJ2cBP'
      'sOSfzT+f6PAYtMm8riKRURIaUoIUzaDaELUwR6LtRWrftb9jMHaBXNJ6VKEqtCLbY72tw9DGMJ+vi64Mvj7BkN3y85WmexyzsRLX'
      'FFibrjRmY73U29J6jawcQ+F46jF2cBS/WhH2GFl8P5ajmnog0lQpDxJCi3J4alhTf44ydY/K/2BomuQTQivUWqlU+mjhcj6wKkmr'
      'IWBSN3fRHmOHI3IcJIhBaUlhlPWfXrCK/QqF1h6l59Wd6vHn15ffrGw8hpZHFNPPFVNA4c+f1+e+EkftfXwATx07NXtS10cxOZku'
      'qs938Yu+MvK3mmrh36v7c3g4Wbt2/a94OKWOFYMEKF0X8XCy5JJW4jaS10hBIfNe+UeFGHGsftB7PJ8zDNzh9uQOzOe8nvt8nubb'
      'eDwfhX+2QelIRV++v3xJE8v27M2/r/5A45/zLznc+rOUDz8pzAaK+av+NZCTT/8Hxd/suyJzAAA=',
  'qr_scan':
      'H4sIABLmm2oC/+1dWXPbOBL+Ky49EywCIA76be+nrdrd2doXlx80jhJ746skzcxOpfzfFzfQTYmWHDuxGMQVEh9uNNDoBoiGvix+'
      'XZwvRKtavmgWH9eLc941i5vHxbl5PZiXEs3it8U56wy+Du/7O5Pmn/86+9PDh9XZT1fL+/vV2qT+8OGDS7bcbFbbzeL84rJZ3C5/'
      'X62t+0sKvrk3b9ostr8vzvuQWc5ks3aBn02aL4sH+1i6VJ+Nty375n/GQZ+axRqExZDOhDyGEOpCTMk31sOEdq2UqlmYcm0GD8mX'
      'c+58beKty8vWeBjaQXDZUK5a2ssu/WNNZ1q2Nekvuob0fatNeud147zM3+VTc3SxXMNy2dCKXgz5nyzL7coScyVsuVvfa8+24enS'
      'E42Z8peAmhdiaLXuG6paNghXkqPuk8u1jGj7JPwPkeSTze7Bk/F6+bjyvW97e/HJ9vDN1nfKvR8OLmBzvQhFxK5PRTg6Xly49o6e'
      'l46eE6G/2lAitG+ObKnUJjB6kOSzzyNgk9PV4ny7/mX1lGnmRu4/ltvrM2pqf3dv0B/+/Me/nP1ndbV9WJ/9ZBt/Rs7+tn745dFE'
      'uDbt/bi83axcH31XcvjeVbpVPbdt3Y1Jz1rGB0cv6PPq5CjnhNx69patz63b55HogQj2TOvZy1rPcOv5N2GFPdgzwjDilWf7nr+s'
      '9Ry3vn+L1u+bBw6fGJ5pff+yiWBrJ4JHOLN2adrdMT93B8zJIQLfJytlFEZjAatspp93JeptyHJXiIiE+Pd6eb/5+LC+W1gB47xc'
      'y920cP/ouvYqsPfPdyk920G5ianz42Jv7Z0S4NWIkP8nG/HRsxQmJHV/XdsPQ3IPg45u+9cK99/gQNPhaUx1YrKww+Qyk2M1Kku2'
      '8jJTf+vqGCi0/HCzut+e/fXm9nb3BGqiPF7fXNmBRGysg0dSmL04bzs6TI2ponrlsBrpURdeo3HPS6fCXFjaFMrNhddu3DPE8FpR'
      'oV/FYVqqSl+Zc1ShyqwLbSh5H88avfgWnMF3cgY9jjNeQ6kYT6dxCqV2HAkrGCg14lDqgP3EGKryeirSZrtwGYOB2lJGhdSSqV50'
      'g+74YMYDy8iH2jGimOgHM+plp3TPqUgczPdPfrYjfwNBLPfj7ZWj3+1/fbfc2nSps/xSZrt++Lx6joV9rB9YGLAw5NlXCINLsFLl'
      'tsIbP7+4rCxFwaKTw0VnWMG+7qIzkD0uvOx7kH1ad9GpjpTcTdSyN8KIvsNVl1lDWvm2Y4awIWqfyklFq80qktLWaddWDCUQwgg1'
      'TRYlduE/0KTC/KTCvsFkQjvZasVNHzAzc9OZapnsvchSzx1yr2wlJVshYSvavpOWWRinnjscbqXoDTTdx6jjFR9MQnj0qezzNuyj'
      'Wi6p1ZYd2atYfuvtrf1yh0wJHiR3CBA8BEseUkXP2/MO60KXzFHy8Ene4d+Dd8iLRQ/Bsocg4UOw9KnC59swkOuEOcqefpJ/+u8j'
      'e97rc3rD+x3W1s8qyiyHjYy1q2Lh5yeHhXkpL6ONY4xZEbdw0xjNQ5tKZmgL4UVkmxfLmWKconsYM+sKV4zC3Q4xRCk7VBqsC6yo'
      'TwlRbJNHrrXBKWBIpGGAqcCucEf6jTx84rf5rPnx9m2m6H7/hCTwjr9rxCF76UftpPdDqzR3mzqSz2z2FZOzr/i+s+9hn/cGOJkI'
      'OJeIcuQ3MfIbMcKrfNCuzypRf9i+8Et4Ky+9EAzOyM0BRm72Am6Mk+AL7J6wQILRit1hjFN+Hia9ZA8uUhaFZCcFc1EU/D4FRBTm'
      'jGDSdGBGBJZCivKdW0N3qj2aOMmAtDRMXWKpr4cdHikLZiqh9Q4PVoDcKp8c49SugJOKFuMntSbUcOSRU3iccwwJUomhiSy2XwI3'
      'LUkjIcE1hqlQHxnBXEeB9FAB9VDf1QiiAYpgjAxzGoAKOgAVdACK9JBV7JIgiFie9yJCfZn7+dXPSTlhendn093loxN/X60/rc5s'
      'lpvdgtqoeNvV2mTqYv5gKqsyKqsU81RZ5eSBInkKKmsUO/ZVyBGEIyxRXbsdxwiDaJWQjeGHQfUzYwQ1uXZTdeesPusaqj6/xwqO'
      'GUVT84YZDVJbfZOZ+VezEab2pQts9VNaYCv0+oxVWHgEyOPWqM0WoS65CAxw+8JFniMco4c2jPBz6V2leemBWkVys0OW2cOq0WqH'
      'R6JcXHKNPFKS5BGLTR6xYmmZjD1iU+yCoM8wLCgjDNpKhE5bKejqFjSywGF5keOj0sioPiSs87NHIszYJzaTOGoK4DME+o59Uj5h'
      'VIw8Uu3QKEpZjDxSiliR7BHqOvLg5dJ3GOEuOzlasmLcZUoXzpxh6BRe7ijoEe5S92ZXihOGAYRdGi7ZlaLEjuXFElIXOToyyBHu'
      'shMxH4JpPvAwTxc+McYxeqiGgrtGCKbEvk0YJuYKsRGzZZ4PVcEYTQEBV/X+yE8zqlWG06Sl3sy0ez2p3euq3Vft9aXaWfw8bKey'
      '8Ck5ClJeYBomxA664zwZPyor9FUfYx53NXiWHyXu2q4LX7Czk8e9VR8JQRVq2hUuV8XiOz+CAsI4/XalM+lUPlKCviEIpnQoR1ge'
      'rAysPWwaogYiFqI1InWAqZciFuD8QerweKTCNkjlzAOuMug4GUQ7u8fUaLvXOsxMCA2TQmg4hb3Wic3UZnojtjLCkYxg5h/dy6bv'
      'W0nnttlKu2kLk65+d6i8UA5j3mpBLS8IOrcvcPQZaytaeaHyQvENzogFoWfKCtOmU5TVdXrdE6hPOPWWy9PiKHuAXXYSFERQSr/i'
      'ZaWH8B8OMKbphJj3SJsUAbuCyhxHHodsc0zmYFf2tMA4PFeJ5g3o0uyBlqf59Rgn+kHCIkShwQKEcEMh1tCjWH/UHE9AiFLbMS0Q'
      'rXj+COF3YApnzNHHgQimV2lvCmxN5QACG0dg6wjMk8ACCapjxKioPMK6wo3Dyn0aVpAne6DhioYzHO5VDzlSD1GtEqKR9gvM7Jan'
      '02aolL8fPeRw2Zq2cHg64OwmOMuaCcGwuHcNomalHgRX/jmOf7RolWTzPEtHp81QaX8qS1rRsLh6Bc5kpCAOOKRdhz7ezhGt7oRd'
      'wlIl5jb0p20AqXj/S9ivX66Vpkc6GMWkoyLebkIkBoIofnRzaXoMCTMiKJvT7PCgwJpGjHCoS2XZ41iW01YZ6oqgSs+LZeU0y8oq'
      'rerQn6m0mrZ6oOoUhj7zYz293HBndagfP9QZb/VMB/r0AUBaTwDWbwSnYQsSTRiy/T4D5sQa2hprZIZcWCdns2UNjOs1tLofpdh3'
      'OQiy5y9s+OP5+MIdCwpH6RHMZuMcuoF5PffG8z02rwceYqd1ekE6UpI0glSfgJN1eoFVgXOxLmMEcR1QKxAcoOnHAC1DEITUFqO7'
      'ERSwZO+BJXsPLNkLEwN4QYQo7QkUhp5SVdIeqVQKo1TSRhliKjU3WTt9zpEO9UBLZQXw0xpK6UYZ6qm5mZ2w6XOOrJ5zrKxQsgJt'
      'lTXMnSUrTB9zZPSUv6ki206yG3fZyYHaBlFX+eYlIsRoptbkZm5GI+yZ6+TZSZiNwENPu08FJVO2fKJoqLdK1p2ak9ujmTxCuNOa'
      'sTC65ODsXZcv4kj2jSqcfZMIlaf6FEIERsUwXqWg4OUS+IRdiA1P3PFdHiLbRkp4NlWNYXnAr7jXAQd30J2vlEA3ZqBGENyK3ede'
      '+S6PfNA1+ORbNoIHh9dnjzA8p8rHHigBgvAYKx/hfNFGcQKV74wQPeDp34MOP9ZrBr+JFmN/uow2vGsFm9s3dsanf7iU1+8vVReo'
      'T/xD00CSB5jUZFY6U6TygqDxFUMSw2RqAIqioCSaLloQvgRVnspSGKZa+ct9EFToQmSMs8AqrgrixVW/e8PRXUIxfsJhZwrjdG0X'
      'zJ7C1OEzVYTP3VuE2oKqCikByVTcSFXA2DHhciiA9l8QxaGxzd6bylCzxhhWPGVY3E1WwBRbFNpfHlXl/WEY5PvICpsQgW5GQTdn'
      'EUQFUtKo7qQcedUxbbWaqQoyfSid9fX+jcoJo714Ks08IufGCtOH1NlJ/FIN6VspdeOeJmgXIhESgCsrHHks0PKAYYWO2m32ufHC'
      '9OlvdhKnv4lue6Np2acJGYPgJhm8z331Q4Uga6k2+rR9OcV2NybJgyCfut/13qaV2YlYNb3hdRIn6yelaDMlgauIPfaGK9oKe6e7'
      'bOnsDKzY9OF7pk+BF/bI0Wa/7D19ESuOFrGiith3O63M7beu2TAtYodTEbEKidQxLkWsqiL2ZeqmcD+qN0sJy6fPGfPuRCSsGA4T'
      'sSbe6ctYIEL70Sq19EkeEFcZ+17mlWGeIpbTSRHLDzu0bZv16BI9PNrJyDg2W4ddXjb8brn+vFobqlxcPv0fQKaw9VCfAAA=',
  'report_success':
      'H4sIABLmm2oC/+1dW29buRH+K4aeWoCHIId3vzXtNk8FCuyiL4s8qI6yVn2FrOw2CPLfOzM8F1I6kmVbtuvkKImkw8vwPt98Q1L5'
      'Ovt9djpzMkgzE7NPq9mpV2K2vJ2d4scNfuiIX/6YnVqFn+ft5/UVZppfL6/m6+XNNWb8+PEj55jf3S3Wd7PTXz+I2eX8y2JF37/2'
      '0ctr/NRitv6CgloxvyzPLlDC7Xy1uF5z8N2KE11g3q+zG3qb5wCWtaSA/+JXJaMxWM6X/vs3kZPnWO1DH0vfMXbNtaA6KXx8siwj'
      'tXZZnlZZIoaCkiH5GMoYzLxESVpjxtWeFvm+HL1RAzPUry1dQy6g0d51ZZvUN68rUmHq27ZIlYs01sukvcifQag2LWDSeZ0UQpTK'
      'GAEQJOjYJ6WG3O1viCjeu0YJ/LPdMFG8d40U+KdraJIOo7lhoAT+LXrbRGmjslV/i/Zf3wn+G7XsJo/++fx2kaclTcPZbyucfct1'
      'bsB1nqcccXc+a9vazcW+W7ipv1IlP4ji/QM3bDT8dwpvtDPcm0q6GDGycVpaZbGuQL2LITkFiKYLwrxns9NP88u7xbdhlHjl/HO+'
      'Pj/RWMmra3z6y9/e/XTyr8XZ+mZ18jO18aQ5eb+6+XyLCc4/9iLaVt+tZyy4HGua2jYorBoYB8lqzaOnnY8egnUqYUdjSI4akmL9'
      '23423dD2QmkkOMp+YzVSRDmXYxzGXGJVcDpf/oc//n3FabiRP69XNxeL8Wa+X81vz5dn2NCcarSlaxrf272zevf0V6MTvo3sZtnQ'
      '9lWVQHWTb2enBBJ6MZaJuutuPhbjuuH/ZTW/vvt0s7qa0TTnIB5v7qvrW+7JM25X36PtbB7pyF3zZH0122y3GjpksUcD9Et5c8EP'
      'qrRd38ATr9TLO9Z1v55hq0vVMAhXXJ+24W1PLa9OaLXcjc+jvy8v14sVTiNKWHXDh00sJAWSUYS7lCpbgRvU4Pb+8uaPk3/M7wjh'
      '1hn7fhB0q+dKCUJbbUWJ0XD5Cse8qBqqSeVzRNU8gCiTV1b79uUE2CCtdx6cyi/glbsmfUxaFlWVaLDuyekcQQocjHQ6CUjSghV1'
      'p2HZIZetqxoZE7qqJj+GT16qYJLDXuaXFWBAquhtH+SKqgEicAqiMUaG4IaqYc28Ec5Lb5MYFgXQSlHYyrb3E+qvZDAjKCudjUO5'
      'XtTLZT5mAoQtE+C1cN3KfjD5FcR2SDcL63ktivcnVYc1TjfByD4qXlGMBD2pPpq7sH8fqQ/OWq1SN9C46sriEXNHgp65QlH62PWQ'
      'ljgJ8/szF+txadhudUlbDQKuru2gQlsFhSu/ABHg6hQvECNBL2I6Njqh8ecSGX35W2sv5ic2D9uvlWk5Gi12CexMT1rnvGo5aftE'
      'MuqI9tG3Zud69fmoVueny+ewOu1uA8tlRNK1TYl4f3mfRUlpDrYnNwjVZE9uzYAHG1Jm25AiG2r9WBtK77Z5Drad7pcxYjPtsMK8'
      '3bTCAmwIY+W1bYHFbY7/aMOLNHS2ZkKsLa8ApeHlEltOuSpaVsCMSJg2gsJg4QBk/aKNzujbWThNF9MMURsthIQQ41ytn/V+wyYj'
      'x841djgAvIDnwFhEVBxhLZMNvcfAOJwcQcSIw49zonYqNFFG7PAG42zqszRGRjRkm2QlRNMrfcChSgnDreVUSKgERP6q0UD0llDE'
      'RpMTGQ1vXO2bl9X6ap/j7I1p+jyInaY3L6npba3p383PLn5DqdcfT/66XJ1dLk7+9O7y8+LPszdEneMz0OZu6qREy3V4oWrdDlIT'
      '83sI80sT7Zto30T7Jto30b5Xpn2+NgZ+ulxcLa7XJ1rPnon1aQJmcwTqp0HGoA/jfkrfx/0gSAtbVoTzx6N+LfOrvduaVO5A+7RD'
      'w6KDooS6RVdASEGVH75wbGtnGXN94W83OajxtUsbFz0Ya3rbyCMd9LjSB7FGIbFmv/ke5hejNCGJiOaDgTfDARsd0BZKyI+xe1k1'
      '40QKFntJo0pWYWNruY7lHeOcv2EBcXzfGZBSYvcZ7houw8uYLO+I+GCIdGLnKY9SrExGtwEhcUA04Tvehgb1atvQPGNjnrF6Qo9d'
      '6EEetQwf7Ftb55Bx/Ag78ENN+PES+AGQ9uDHYbyV8cMlqXQSIchooXAaBp19hjYWEGKlT87oblcUAm2mDgASBKSA6g0r10GKuWd3'
      'lDaGrbBUmH0DUGIkRI26GpW66xFAs4rnqNJRSCk5agjMKTkORo8y3ZvNDN7L+6rSOyejjI4335WjlLSQsK9Mkg44i0HTwQSpVOIa'
      'YAD5ihOSUWpP0+ZvWIDh+mQJDYnQKdeQhDQshaAxC2EZZuI6D+M65ZKYsOoYWBXHsSpNUPUiVCfugipQuBT9ABZ0vIiCHAQVe6Xe'
      'Q1XIzsXGyX7ji6HKQw43qt7dMsRlbODDSv0+FxZeQIYV4NA2hP0o5RUd+REBFeHb4Ts4dSLyDNDZY0KVC84IZDWGoUUqJDP4rlyP'
      'QZzEchLW81kES2B/GO2F8Y6YclsHbkFaRRtgqPghl6Y9ggwpXxYFSHcEch0XPT8blBU5IOjvmPTo1zt7W87aCUeOgSNpHEfihCMv'
      'Qnm82Ud5jCsUrRgJ6nHE+owXUW8ASYoc4brwtmWYXkNNfJLGoDCglMDpQ/6c4ezpfkSxSJPAC/5wbwBSGjqLYpmDJBtLlpM01kgm'
      'GPxhUjviD0AqtEoZnSBI0cNxCpQaWKgvKYy1BCQ4BoNQ5BWJNgQRtIbSLcITMB75gRY12KWorBNyFlPIdD4JFAl2lHZRDI4hphqk'
      'kwSsG4krpFNhILjkQTpXS1Adi5Mi3ADBrSl7gY4Zc7OHQCCzgjvIF5yP+o+29xCZ+lDqaE6pTdWzqObbESoQOUhHZ7ENzvbs7jTS'
      'EmNEFp9iaEfKMmnTfCoGK0eeSWR1ARjDse2YHj9IMD+DozE0uEyoUURVALjoPC7E/7AnGkR15paG9A7ywIASWUKUwdPiRBOCuSd9'
      'QZuEgm12sWJCwdl8PoTjXCanbRuopCBywa0dYbDEXDUO4NoKrjv3DrVGC24bP1NrPfery/tz1Bui7R0O8ZkAc/9N5PVB5LVVaPlj'
      'MjqOYXRoNW51hMnqeH1Hq1egYm11eFOelxisDp2NC1RhquSueacu+H1eVit1Ck4gmUWLPhWnUvYbGeTTxf7B7CHYN7RPR/xTI4IH'
      'RuMmSSCDAIOz/5IwWOeTmTCc2txKxmJE04nJmSiP2eKukfb/BHA/ddjrCdccwpPPyBeVo7ui2CuxDWArByfqtGf3LPS1mr0TlBwF'
      'SvQ4lPgJSl7XEZrZanHAw4mRoOLMB5m8tj7mT7jSwckeFygmowMI5SVJoH1xCIMf9sfhruZg7uqfxF3TGHfVmbtCzV3NCHeNB3HX'
      'UHFXk7kr1NzV7OKu+nDmqivqStchTMcot7hreEHu6lruag7mrnqTu4bMXU3HXd3juKvruCtscte0yV1T5q62565ug7vCKHe1E3ed'
      'uOv/v8EB4waHmwyOF+Gu0RznkBAqlMxeS3ujNUCQJanCVx7oTonShcGhUDGGkiej6eKQrBXO8njPKSFiWVq0H2+ByPK5T3bc5i/d'
      '1YMuNMeH+uLBdqQYF9VfOlCMYe2dA35gECiD26cJCx52CKeccRMWHAULzDgW2AkLXgQLwrGwINl8MjT6evtU23xrEdTW9ina4IVD'
      'M9HZj/raIcoMyFN7BhruoaCo1x3awm/Bq4m0KwJzJJ+Ku+f4xD7MCMVVAqydqNPlbKJMt/Hjdyz93kwi1yOO1SN09ehxBVkEX32I'
      'OPGJquDIJqBjqe22nsNpHchDy9yLTohqyx4J5X1HQ3Bw+vwNCyCPakuuGhYR2T3LMloRTStjQqsHMZduOUxIdRSksuNIZSakev2r'
      'caNu0vFzPo3Wpv3hE+tLR2nKOAXSFSgF0uLCjnqPo5R+M9RYTGJbWIyTp/QlPaVmzFNqH+EpjWOeUnOgp/Txp3w6V6k/2FUKz+wq'
      'hSe7SuGJrlL/YFep23CVttdWBl+pm3ylk6/07VkdbtzqgMnqeBF+nOBY/Ni1RgeE8mdmKSy5ylNa/EyRt1iD4UdlCe21pft2zh54'
      '2ofvjbnv4CqlO/gqpct3IvXuq5Qgavlj2aqrlHakKjB6ldJ2VymN6O9B0jVI0V+CrK5Smq2rlHbzKiV0Nynbi5SpvkgJE0Y9/CKl'
      'my5SHhOjdv1qzHP/ZtyBWPUAgYdj1qEiXwu43JGAi/1zbuNOjFUiuA1/rqPjkhb08Ktfmn/ZcnDf0lUNJ/Gf76ly+JG2+MK+Lb7w'
      '4C2+fMlF6WGfD/p9viquDZqA4tGbfdNNyUcBBSa5mq8u8n9D9eHb/wDyKqzV7WoAAA==',
  'speaking':
      'H4sIABLmm2oC/+1dSXNbNxL+KyqeH1DYF98ymUzm4ElSmczk4PKBsWVL5UUqik7icvm/z9fdeKsoKl4oe2xWJSIfgAd0N3pHg36z'
      '+n11bxV11HnVrV6cbtere29WT9F2/2K7PT/9x/nz06uTb747MdpqZzEGA1b4eCYfj+Vj+4g+33arJ5vVPRe71fnl6p7pVhf4SKVb'
      '/bG6503oVmf4zK5bvXyB8d9evLg8oSkfP37Mo9dXV6fbq9W9Bw+71fP169MNfX8zdJ+/xKfFYq8xS5vjh//cv3/y7Y8//PLzj/dP'
      'MNXVhoc8uyI0LujPmt99JjP8iV4LMDc7ewx6Lmc9D2zwOsfOptyZhzLMvWUiTEdF0+G/fgAtcLWYxpiu/d8Gpbc0zYUsPifW1ZYf'
      'fwN+gGiBvxP8Q8P/Xz++2p4B78v15vTllnHfQwIC4T2IEJkG2e8jQdagUnl/GlydrS9PZb8Jv9XTDbA633IDI24EcQxctSV6HIcl'
      'MBLjHyjwqkkdPmp82D1QVeccCLIHymoDIKuOPuART60j6xQtvgGwC5oCPZHGherQW3UxMs5oUxzNnFPm+YIudZy7yBS/MxS26ILB'
      'VVtX6NXOJVoTrZVaDUOQ8ek7mSvpauk7ZoA4bTevTt+O5Obd/mm9PWOJefEST9/8/W/fnfz39NH2YnPybyLfiTr5fnPx6hIDzkCx'
      'J+vnV6fEQEy3J89XPO90S4wuuQRvIZMxVGNr6owOiyZsu7bzJtvZtoXhbXcTj0VhMds4uaEAhfJ8Nwrfb9aXZ+ePgASN2YnDlphi'
      'wZy029A41ul4M3fSIO86UNjEHRxqZRTzz5vVn0IZT4jjL8a/XrT0SMtIVg70dxg5tmCkSDOxdiVF8pCwOdA6Rdax9tALWTuuVPNB'
      'V3LjSrkcdCV/ZzjVu9onZ8aVYjjoSv7OcEp3tU8u3xXvuYnkOnPIlXwYV0oHpZ7Pd8URwdwVTuHOuDxMOKIcdKXYdHk1nT8ok8fG'
      'ejl3+aC7FNO40EGFKeZhIbiaB1womWGhcFDSpXGPnNgLaswz/6U5UP6mECLd7BNmcrqe7XqJHMmr9a6e2Hu/v2zWL6+eXGxerAgE'
      'bmJ39yTAK3x5ybHRI3YAB5ezxQk7fM2lm/zw3cIwPw/D7lO0emLNoSOxkDR83Rj3RWIIRA8Thn1wXGZ18laCJWe1q/I16oyQyulc'
      'K4dJ0q99rhRomUxRE77E4DgQKS3uqr69b3SqloamHHkCrBNrGuaiVVv0RsuUIl2LQXjdcfj6ICL2qzTSlDj07/irsxeIeI2CTQEM'
      'vljuiwK9K37PFMAiNCy8TggxATnQnowawTXXgO5j1QX+CClLtDNAfS0EaCDQHIs8EbYSaElH7IPy2vLL47ZMqWZ2EGwJmyIM/IiB'
      'sqAJbdke/IlAIQowWXadiADqGd92VgDfN0fQHiEqver5pclOXod82P8JL/ajGtsM8XsiaABdcNpxBK88Ykw8F+FaS9+99vIcwA6W'
      'G4TOxLlVXuZcQ9AJ1OB+Rm4y17WFEh58xcy+f0g6xDwZ6j04jJaJgCOAZp5oRTsYsQClKIZXhoaqXSrjyl47JmzV2Ui3cVWeif09'
      '5ynac+L5qkmcKome+kGtmBix0hFlkq/Mx64mhs9U2dHUnn1KQqdYMr+QZb8yCMTTheAkW1Oy5/USp0hUDwABVKQBnC4QMw+rBUZq'
      'hnKdtfRUUTFp69OEcOoabdWM9GqyK8cMzbtkaMwt1upWW/UZORz/3r568uQjuBvdh5vTQW8VnZLts5Fz1c/ZR7YKYNwSJ1ZDDS00'
      'LENbjWYJxjfF5exmktt08q5iibWkViElLJwu65qhBy294vsv0U2GkK6w8vJHl6PpEcFIQncTCUGw7OYEA/LFp+aiZOsXJgLGNPvR'
      '9LbMr9fV5cWY/q3ZNJjdQCP1dCQCEd1dgSF08h06CURkY0x56mYjQLSQ2/fYD7mFfO6ohr5UNfTz+dOzbVNDfqcacp9YDcU7UENq'
      'okrIpE+1jPKBHJqmgNSgitRMXamJJvvalZHqtRF5QDmW9hBHhaSmWkhN1ZM6qqSvXSXdP32yXyP5d9JIXzq5fl2/frLeUInDPpod'
      'JHcVduWuwh2krhC1SXbhxj2kOM6lzzN9BfVWMx0hc9CJAJceonUcE3vJokTbQmQYLosAtj0ZShSFQE9FI1pHXGrZHCLgt5K7YLun'
      'A1kzC81W5VGyI9k7SThRYGwogJZ3Iw+Otj16ygPoKtFs1J4TSoDTtISHK6WDZpcY2aAdxkbnIKGujgGakeobSsvEWOo2VcL4AlPh'
      'gZKkECg950sHa5Da3IWDeB3M8Da97IssFcjmNMLBILkCS19dGkxXxIuwIKEVbADIROYHb0hkrqsh0D0TjTIGlKGwBDKvDmhcI5Rv'
      'uR1DwMKIyfo1Z9qOllSynA4rtT2GwnSQpBV2joba0mcvUsLCzjnJXVia11PWSjbE0ODMCR4j+2GGR2MipzWdZN2EQVxphSfCIAyD'
      'pWW4qiTyYMuOS4R19ZyOdICh6sLsw5RVPWmJCSlsgI2PDRmYfjL6zrjBsEfOo6GVqlo4HAsgJbU4pyO3+EhrUws22lvJTVZiL4f1'
      'rZh4gEuTw+5XxzxE2RBusgksy3sRSAZoIks4SsYnCSmsiboIf1Aau0FUs7RQYgUUqpT+SS1lw6nJirecJHEoA4TlCkBqSZzC5TOc'
      '+om+vVUiuSiWPENuwa5RIg4Yxra2pXdygnuZm1djiaEqJYBEYnPBiAImoXIRzpiRnBbyeGiHAihOyaMMzmOMYsQrllN4hrN2seoU'
      'CnlH2rH/lZyuJNyZXDp3zCB9tX6SHFnZj5hD+uJzbmcXm6365/p804hmP3HiDVqvwvZbW0VbhwBtXVjbkartD1CMd2TqTRRj7iwf'
      'U2TWpoY0CT1aVqWwAGLqK+uXCFuV6YCFTXuGiaKjA1hF0U6svL1OnH+HWu7IAIoDkTKZ5SxhtLbZ4slWsVbeVO6T9Z3n2kTTgCPt'
      'ZenYSobCVYALUUVlNlcDz7UdxmU2bcU1++o5Yw8zmcR8O1LcpKVtf6ojJzRsNhlpxr2d+mDeifUDxWpfUgknBsYkwIESRQ2AyBxX'
      'sSIwHrCM9Hew3YRu7L2ODJ8Cu2Sav1PgH9HpTDP7sRI1SgpjLmKJ94Isak40NacoORYwoT25+TyuDnuhptukFluIZ97+focV7X8a'
      '9l8tuEMtmEcteEstWE+NTKnm3KrmrDwlSvdgTrE5Oee0nm/EfJfmW0h7G9spa7V13PUFTyxYZsFRC4absyMxa+iZtXeBEpChU0JK'
      'ebBbAM+B/WU4M+IQkwX3fSoJXgQdklIiK0n+GpOjEyEMr4jnQGeMcAT5CAzvwjFM8HNty4GDOuTGNumKfPYEq8u7mebdKoTZ6yra'
      '2ez0PFtdYfkZeOTjjMCrmBe4KXgjJbkJ+uQ5RVrSilMcE7vBlIIScaEGwABUbHXNQUs2d/Alg0g1oIbH0GFgYubh07YcugS8vCDq'
      '+Qw509m9sBCX0YFAAR1x7Ahm/iboOZuaHNjp2kBwBhw9T6GP5KfZht2nTusNR93sBNOHa+EBOWJG/PR2kG+ozLyNuPbGorbcQiUT'
      'KxmJgdBAEVkalONshBChofBR8nLTywgjFfxfoILtK+lbJCPgDRQYGtvwsYSgx95CAwcnqCVJKtuQ5Dn2z0P/baj790PdL1EPt6AO'
      '5R/BozAxTSdz6Qf+9ibVc+lD4OiRdHvhaorkfTPlmXRcZb1dWaFzYCthIORG8rua6gV5Ld+cDgdVHGMLZx1BkOJo866tMwNjDuQc'
      'g8lkzQTNVprBQbrOJ6HDAna1QG3J5nyDoikUy6dkCCdLU6uwK6JQZh3Y/8lb0EKBYnqSByu0g5n2FOO3Uh1SJBzz0iHDtE85N393'
      'BtBtjBWOMdzXEcPFDziAe8fUbdyVuvV3U3Xo8v4dVO4zuf4F7zay8+gl1OrrxEqk2Mi3ZGosYmmagxksKRBXW+4u8/0xm8PieC2y'
      'pqHawKY8pJjOSehCSTN4tbZXF3QRjVexpTny3sCPAWDjsZtjrx/uYIYrzMoM3j9pRDRYToXRFUROr8Jn5XQsVZ1RPgoeV2C3mtaF'
      'BeTsV2gNIQVpKPaYbTpqqs+hYmmnYM7lUi0EU80lU+0RTTWXTbUQzoVsLkRzl2Sqa6Kprsmmuiac6pp0qmviqY7yeZRPbvru9elv'
      'm4s/9srn+5fyTALVU6Lvkhyuo+PLgZQLOjsq6igTYgnEz5+fX16dntzOmW3kkTf/r22H28ub/hPxpjoy51evOPcyZrjb+kfK7w9V'
      'd/IXJh5uzuijyHPfPx8/ZjwoS9vfVRo/WvNtKYejo/DF8vsPF1f7GT4eIt+QduUb4uoQSQYbTOdi5YTb3m0reTbmU6YaqHzFcaFT'
      'O5j1FAlE+tx3c3BS/xw6KoC+dbicolLNjKF7a9MLBFzjBGsI+lE05dqXiBY5DDEdH0iigbOjHmFOPUYcx4zA55ARUHMJUu8jQuov'
      'y9BOEVK9DKlBiNQgRWoQI9XLkeoFSR0l6euWpF/PXz49UOD+nndwJuaCagj4QrkdrtTM02X95fgQ+PzPFLeULhaPUDvLRc1UMcDS'
      'UOSnJq43JMnVcQMnxzJ2zIajhHy1EvLTxaNnp1t1tn757PWB0gjvKClUom6lEKYsRMZnnStVXUnxt+ECG2/STrkxnPH17fAI1guc'
      'TvcD5GJV1M5Mb3nC4JRmUXiTxm+earKd1BhTjRMcYMpss5tWy+0Xqg5evqI834q3VFNfB8RTyTfY2RF3Mc6UF4eFx+sLBTP54YjF'
      'ljDdXZ5aaLovwbSRQvw56XY+ivmm2/0D6RV26a/Q9HhJ7cstJV4/uth74erO0kZ0o7MVZZpWyhfkgubQ2hqHUp3rXd3uaXrBodoW'
      'T7+UE6TIzvrYJfpZllaB3JWis1QQ+jrtPVrsY87/QzNNH6XQ3tBlQLoZ1CwPTHTMN5iRrEP0VJMc2s9AUZlwXwsZhzpC+l2iNN6a'
      'pt+1yVSubG6KH8mEtWtwFKcSPDlMp+If9R0XoHWjH62/12Bq2C7H4ePcVk1M1fLraM/gGtTI5k+sHyLkZNrvDrEU21b67EPfcRTg'
      'r1WAN6frR1t1iV1WIaS9cpyOcnyU46Mcf86G2O8V4HyII5+868gnHezIx9Zbdu0z+UcFLF2qocvHQ3pgl4ap8KfDDXqN+27OTFOd'
      'Of1DA1IEn5rSGErb6Cfv6B80cNfmRevi9w57aLhn2hKpDm1oiHKtyNDl/RuSHJwX2Qf4LUgvqaZma94I2c0oMEBLjHdTpyehmhF3'
      'LLvtAl0r4gtboeNrC5h09tn09236XX4goWs3H4YvYfwyrKQiYK181U+u3CmqL+T8Kn/z/aEDXWAvPgxPZfaNf9gn7PwyjJlNMsw9'
      'LDcH5GhnjseBB/4FZXS/WG+eyT/q8/Dt/wBpBmtFeWgAAA==',
  'thinking_dots':
      'H4sIABLmm2oC/+1ZS2+cMBD+K8iVeiLIbwO3pElzySFSq/YQ5UA3bJYuuyBwH1G0/71jm32QsEmadq0c2MPaeMbz+GyPP8E9+olS'
      'JCIRKRSiRa4zlN6jWxi7qLQu8o9FmbfB8VmAIxJRDDqggKCZu+bGNXpi2lWIpg1KaRIlCmNMKMUKMxKiokYpDlEFjUwibH40JphT'
      'JUP0C6WMhmiGUg46ywVYumyKSR68Dz5kZRtcVNlNsbw1zm5urJ2sbXPdovTqOkRldpc3pn+/ERdLaMGrvgOTncXTSgcMTLSNFc1b'
      'k2Zl/jI3YC0UZuA3dHEUMwbW7zZ9yK3aSolUG6npg1Rb3yYSDI//bIs6WwT/F2tS9c3poYXoYofpBdgiBKY2HULYIoQ7CQZJvQ87'
      'G5SNwPZ2orMBdRLouchi55eyiEoakiQiSRJiiEFXJpwQu4di87CLxl/6IrzvTETycM4o9pgZUx6dceYRRp54zExKj84UfQ2MZmLs'
      'Ti4jCsqsIMMxr88xXdmavXOMr47Al4B50Crbweszv7K2dnWZihJY8K4x9cOpypWxW7miN8vq3NVgU3PRbQOVttCuKG9KMcpL9Mg8'
      'YVGcxKFrdiKu+2p4E6KB1Vb0s7Is6jYPLjM9C4i5vJYwenx6chZ8ySe6aoJPJqzgKOg0QWUG0UzhTsktkiamVsPw5IGziFAiZCyp'
      '4gInMWaAZ0S3T04KY0xRwRNMEolVzBkRIdkJs+qZBeiciK/snbcjok4gQFBOLF7ld9ssSnuDfVtYTZv2J91U83w44fMmq2fFBFJ2'
      'WoMZT8vDZMz3ZyzcTUL6mQC1KJ/Lw+gMZqHNFquf3tb7DwB+asebsLf7nO27BeX+fM0Bb+dDkwxIbTYkEet9/bnJlu20ahbInODe'
      'VjdgLSFpKDITm9kGUJvKIJLVj7oH4PUzbAwORHpEu2FCYkISvvZj0O+RLPqYZNGRZL09kiW6wEQEpPzQJIv0nR2UHRDlMTPGPTrj'
      '2COMXHrMTDKfzpLXwGhIluhIFhY8JnQPQCPJGknWSLJGknVIksUekywykqy3R7K6PJWHWy3uuTosw+L+0mLEoy/lD8P1CzMfeUns'
      '0Zd8BYb2zVd3YBNGJcXDqz5Sq5FajdRqpFaHpFbcnWzSxfl1Vug8ODnfx64ewPRCXrFeFhnS7boNLCqJYdVDxhj8P7+8+0qZ+Zqq'
      'zPuemanP5pIzn2bfTe0PvQA8vAYLrC+yZu6+rl6v/gCJ/nvdKh4AAA==',
};
''';
