"""Add-on A: generate the `StateCue` FlutterFlow custom widget with the ten Lottie cues embedded
(gzip + base64, decoded once at runtime; rendered with Lottie.memory so nothing is fetched at runtime).

    python app/tools/gen_state_cue.py   -> writes app/ff-workspace/dsl/state_cue_code.dart
"""
from __future__ import annotations

import base64
import gzip
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "app" / "assets" / "lottie"
OUT = ROOT / "app" / "ff-workspace" / "dsl" / "state_cue_code.dart"

WIDGET = r'''import 'dart:convert';
import 'package:archive/archive.dart' show GZipDecoder; // not dart:io - dart2js (FlutterFlow Web Publishing) cannot compile it
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:lottie/lottie.dart';
import '/app_state.dart';

/// One Lottie state cue (Add-on A). `cue` is either a file name from docs/ASSETS.md
/// (mic_idle, listening_wave, thinking_dots, speaking, countdown_warning, qr_scan, connected_check,
/// offline, empty_history, report_success) or a page rule that picks ONE cue from App State:
///   'room'  -> speaking | listening_wave | thinking_dots | countdown_warning | mic_idle
///   'pair'  -> connected_check | offline | qr_scan
/// Honors the OS reduced-motion setting (static first frame). Pure UI: never touches VoiceLink.
class StateCue extends StatefulWidget {
  const StateCue({super.key, this.width, this.height, required this.cue, this.loop = true});
  final double? width;
  final double? height;
  final String cue;
  final bool loop;
  @override
  State<StateCue> createState() => _StateCueState();
}

class _StateCueState extends State<StateCue> {
  static final Map<String, Uint8List> _cache = <String, Uint8List>{};

  static Uint8List? _bytes(String cue) {
    final b64 = _kCues[cue];
    if (b64 == null) return null;
    return _cache[cue] ??= Uint8List.fromList(GZipDecoder().decodeBytes(base64Decode(b64)));
  }

  String _resolve(FFAppState s) {
    switch (widget.cue) {
      case 'room':
        if (s.isSpeaking) return 'speaking';
        if (s.isListening) return 'listening_wave';
        if (s.countdownSeconds > 0 && s.countdownSeconds <= 10) return 'countdown_warning';
        if (s.lastReaction == 'thinking') return 'thinking_dots';
        return 'mic_idle';
      case 'pair':
        if (s.connectionState == 'connected') return 'connected_check';
        if (s.connectionState == 'error') return 'offline';
        return 'qr_scan';
      default:
        return widget.cue;
    }
  }

  @override
  Widget build(BuildContext context) {
    final reduceMotion = MediaQuery.maybeOf(context)?.disableAnimations ?? false;
    return SizedBox(
      width: widget.width,
      height: widget.height,
      child: ListenableBuilder(
        listenable: FFAppState(),
        builder: (context, _) {
          final name = _resolve(FFAppState());
          final bytes = _bytes(name);
          if (bytes == null) return const SizedBox.shrink();
          final oneShot = name == 'connected_check' || name == 'report_success';
          return Lottie.memory(
            bytes,
            key: ValueKey<String>(name),
            fit: BoxFit.contain,
            animate: !reduceMotion,
            repeat: widget.loop && !oneShot,
          );
        },
      ),
    );
  }
}

// gzip+base64 of the recoloured JSON files in app/assets/lottie/ (see docs/ASSETS.md for sources + licence)
const Map<String, String> _kCues = <String, String>{
'''


def main() -> int:
    parts = []
    total_raw = total_enc = 0
    for f in sorted(SRC.glob("*.json")):
        if f.name == "manifest.json":
            continue
        raw = json.dumps(json.loads(f.read_text(encoding="utf-8")), separators=(",", ":")).encode()
        enc = base64.b64encode(gzip.compress(raw, 9)).decode()
        total_raw += len(raw)
        total_enc += len(enc)
        # 100-char lines keep the Dart file readable in FlutterFlow's editor
        chunks = "\n".join(f"      '{enc[i:i + 100]}'" for i in range(0, len(enc), 100))
        parts.append(f"  '{f.stem}':\n{chunks},")
        print(f"{f.stem:18s} {len(raw) / 1024:6.1f} KB -> {len(enc) / 1024:5.1f} KB")
    code = WIDGET + "\n".join(parts) + "\n};\n"
    dart = ("/// GENERATED by app/tools/gen_state_cue.py - do not edit by hand.\n"
            "library;\n\n"
            "const String kStateCueCode = r'''\n" + code + "''';\n")
    OUT.write_text(dart, encoding="utf-8")
    print(f"total {total_raw / 1024:.0f} KB json -> {total_enc / 1024:.0f} KB embedded; wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
